let PROTECTUS_COMMENT_STATUS_STORAGE = 'PROTECTUS_COMMENT_STATUS_STORAGE';
let PROTECTUS_MESSAGE_STATUS_STORAGE = 'PROTECTUS_MESSAGE_STATUS_STORAGE';
let PROTECTUS_COMMENT_COUNT_STORAGE = 'PROTECTUS_COMMENT_COUNT_STORAGE';
let PROTECTUS_MESSAGE_COUNT_STORAGE = 'PROTECTUS_MESSAGE_COUNT_STORAGE';
let ACTIVE = 'ACTIVE';
let INACTIVE = 'INACTIVE';
let DEFAULT_STATUS = 'INACTIVE';
let BASE_URL = 'http://ec2-18-191-177-233.us-east-2.compute.amazonaws.com';